# Generated by Django 6.0.1 on 2026-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_stock_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LIMITED', 'Limited'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
